service: farmhouseApi
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 2048
  region: eu-south-1
  timeout: 15
  lambdaHashingVersion: 20201221
  stage: dev


functions:
  farmhouseApiFunction:
   handler: handler.farmhouseApiFunction

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
   events:
     - http: 
        path: /
        method: ANY
        cors: true
     - http: 
        path: /{proxy+}
        method: ANY
        cors: true


#    Define function environment variables here
   environment:
     NODE_ENV: secret.NODE_ENV
     PORT: secret.PORT
     USERNAME: secret.USERNAME
     PASSWORD: secret.PASSWORD
     DATABASE: secret.DATABASE
     DATABASE_PASSWORD: secret.DATABASE_PASSWORD
     JWT_SECRET: secret.JWT_SECRET
     JWT_EXPIRES_IN: secret.JWT_EXPIRES_IN
     JWT_COOKIE_EXPIRATION: secret.JWT_COOKIE_EXPIRATION
     EMAIL_USERNAME: secret.EMAIL_USERNAME
     EMAIL_PASSWORD: secret.EMAIL_PASSWORD
     EMAIL_HOST: secret.EMAIL_HOST
     EMAIL_PORT: secret.EMAIL_PORT
     EMAIL_FROM: secret.EMAIL_FROM
     SENDGRID_USERNAME: secret.SENDGRID_USERNAME
     SENDGRID_PASSWORD: secret.SENDGRID_PASSWORD
